services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=agua
    ports:
      - "3306:3306"
    volumes:
      - dbagua:/var/lib/mysql
volumes:
  dbagua:
